// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Keep Going with Apps",
    defaultLocalization: "en",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Keep Going with Apps",
            targets: ["App"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "App",
            dependencies: [
                "Guide"
            ],
            path: "App"
        ),
        .target(
            name: "Guide",
            path: "Guide",
            resources: [
                .process("Guide.tutorial"),
                .process("Resources/AddAndDeleteCreatures.png"),
                .process("Resources/AddCreatureDetailView.png"),
                .process("Resources/CreateANewViewToShareData.png"),
                .process("Resources/Introduction.png"),
                .process("Resources/ModifyingState.png"),
                .process("Resources/NavigatingInSwiftUI.png"),
                .process("Resources/PracticeWithSwiftUIBuilt-inViews.png"),
                .process("Resources/SharingDataBetweenViews.png"),
                .process("Resources/SwiftUIBuilt-inViews.png"),
                .process("Resources/UsingAConditionalModifier.png"),
                .process("Resources/CreateYourOwnCopy.png"),
                .process("Resources/DocumentThumbnail.png")
            ]
        )
    ]
)
